
[build]
target="aarch64-unknown-none-softfloat"

[target.aarch64-unknown-none-softfloat]
runner="python3 rpi3_qemu_runner.py"
rustflags = [
    "-C", "link-arg=-Tmemory.ld",
    "-C", "target-feature=-fp-armv8"
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
